apiVersion: v1
kind: Pod
metadata:
    name: nginx-standalone
    labels:
        app: nginx
        rel: stable
spec:
    containers:
    - name: nginx-standalone
      image: nginx:alpine
      ports:
      - containerPort: 80